"""Coins anchored to real stocks.

The one lane in this bot whose catalyst exists off-chain and in public: a stock
moves for reasons that have nothing to do with crypto, and the coin minted
against it inherits that reason.  Every other lane has to infer intent from a
chart.

Read-only and pure: this package contains no provider, no database, no wallet
and no order path, and nothing in it can spend anything.
"""

from __future__ import annotations

from .anchors import (
    ANCHOR_LAUNCHPAD,
    ANCHOR_NAME_ONLY,
    ANCHOR_ONCHAIN,
    HUMAN_ANCHOR,
    VERIFIED_ANCHORS,
    AnchoredCoin,
    StockAnchor,
)
from .ranking import (
    CROWN_CHANGED,
    CROWN_CONTESTED,
    CROWN_ESTABLISHED,
    CROWN_UNCHANGED,
    LIQUIDITY_MULTIPLE,
    VOLUME_MULTIPLE,
    Candidate,
    CredibleValue,
    CrownEvent,
    CrownState,
    credible_value,
    evaluate_crown,
    rank_anchor,
    summarise_anchor,
)
from .registry import (
    ROBINHOOD_CHAIN_ID,
    StockRegistry,
    StockToken,
    build_registry,
    normalise_address,
)
from .signal import (
    ANCHOR_HOT_NO_COIN,
    ANCHOR_QUIET,
    CLAIM_UNVERIFIED,
    DEFAULT_ANCHOR_CONFIG,
    HUMAN_OUTCOME,
    NOT_THE_LEADER,
    PINGABLE,
    STOCK_RUNNER,
    AnchorConfig,
    AnchorHeat,
    AnchorVerdict,
    evaluate_anchor,
    score_anchor,
)
from .stages import (
    STAGE_DIAGNOSTIC,
    STAGE_ENTRY_CANDIDATE,
    STAGE_TRACTION_WATCH,
    STAGE_UNSAFE_MOMENTUM,
    STAGE_VERIFIED_LAUNCH,
    MarketState,
    StageDecision,
    classify_stage,
)
from .verification import (
    HUMAN_PROOF,
    HUMAN_REASON,
    NOT_STOCK_LINKED,
    PROOF_LAUNCH_RECORD,
    PROOF_POOL_PAIRING,
    PROOFS,
    REASON_ANCHOR_NOT_A_STOCK,
    REASON_NAME_ONLY,
    REASON_NO_CLAIM,
    REASON_POOL_MISMATCH,
    REASON_REGISTRY_UNUSABLE,
    REASON_UNVERIFIED_FACTORY,
    AnchorProof,
    LaunchRecord,
    verify_anchor,
)

__all__ = [
    "ANCHOR_HOT_NO_COIN",
    "CROWN_CHANGED",
    "CROWN_CONTESTED",
    "CROWN_ESTABLISHED",
    "CROWN_UNCHANGED",
    "LIQUIDITY_MULTIPLE",
    "STAGE_DIAGNOSTIC",
    "STAGE_ENTRY_CANDIDATE",
    "STAGE_TRACTION_WATCH",
    "STAGE_UNSAFE_MOMENTUM",
    "STAGE_VERIFIED_LAUNCH",
    "VOLUME_MULTIPLE",
    "Candidate",
    "CredibleValue",
    "CrownEvent",
    "CrownState",
    "MarketState",
    "StageDecision",
    "classify_stage",
    "credible_value",
    "evaluate_crown",
    "rank_anchor",
    "summarise_anchor",
    "HUMAN_PROOF",
    "HUMAN_REASON",
    "NOT_STOCK_LINKED",
    "PROOFS",
    "PROOF_LAUNCH_RECORD",
    "PROOF_POOL_PAIRING",
    "REASON_ANCHOR_NOT_A_STOCK",
    "REASON_NAME_ONLY",
    "REASON_NO_CLAIM",
    "REASON_POOL_MISMATCH",
    "REASON_REGISTRY_UNUSABLE",
    "REASON_UNVERIFIED_FACTORY",
    "ROBINHOOD_CHAIN_ID",
    "AnchorProof",
    "LaunchRecord",
    "StockRegistry",
    "StockToken",
    "build_registry",
    "normalise_address",
    "verify_anchor",
    "ANCHOR_LAUNCHPAD",
    "ANCHOR_NAME_ONLY",
    "ANCHOR_ONCHAIN",
    "ANCHOR_QUIET",
    "CLAIM_UNVERIFIED",
    "DEFAULT_ANCHOR_CONFIG",
    "HUMAN_ANCHOR",
    "HUMAN_OUTCOME",
    "NOT_THE_LEADER",
    "PINGABLE",
    "STOCK_RUNNER",
    "VERIFIED_ANCHORS",
    "AnchorConfig",
    "AnchorHeat",
    "AnchorVerdict",
    "AnchoredCoin",
    "StockAnchor",
    "evaluate_anchor",
    "score_anchor",
]
