"""The autonomous PAPER-trading research laboratory.

This package is the trading *brain*.  It is deliberately independent of Discord,
of any provider client, and of any deployment: it takes evidence in and produces
decisions, positions and reports out.  That separation is what makes the same
engine reusable for a different instance later without rewriting strategy code —
and it is why the package contains no network client, no wallet, and no signing
path of any kind.

**This release is PAPER only.**  Nothing in this package can move real funds.
"""

from __future__ import annotations

from .authenticity import (
    AuthenticityAssessment,
    ManipulationGraph,
    SolActivityProfile,
    WalletActivity,
    aggregate_sol_activity,
    assess_economic_authenticity,
    build_manipulation_graph,
)
from .bankroll import (
    AllocationCandidate,
    BankrollState,
    BreakerInputs,
    BreakerStatus,
    SizingInputs,
    SizingResult,
    allocate_capital,
    evaluate_circuit_breakers,
    size_position,
)
from .config import (
    CHALLENGER_STRATEGY_VERSION,
    DEFAULT_LAB_CONFIG,
    STRATEGY_VERSION,
    LabConfig,
    lab_config_from_settings,
)
from .costs import (
    ExpectedEdge,
    RealizedPnl,
    RoundTripCost,
    estimate_expected_edge,
    estimate_round_trip_cost,
    leg_costs,
)
from .decision import (
    ENTRY_DECISIONS,
    Decision,
    EvidenceQuality,
    Reason,
    SafetyStatus,
    TradeDecision,
    decision_from_json,
    decision_to_json,
    human_reason,
)
from .entry import EntryContext, EntryEvaluation, evaluate_entry, why_not_entry
from .exits import (
    ExitContext,
    ExitJournalEntry,
    ExitPlan,
    PaperPosition,
    apply_exit,
    observe,
    open_position,
    plan_exit,
    position_from_json,
    position_to_json,
)
from .identity import NO_DESCRIPTION, TokenIdentity, build_token_identity, safe_image_url
from .lifecycle import (
    LIFECYCLE_STATES,
    LifecycleObservation,
    PublicationState,
    ReentryAssessment,
    RepublishDecision,
    TokenLifecycle,
    advance_lifecycle,
    assess_reentry,
    lifecycle_from_json,
    lifecycle_to_json,
    new_lifecycle,
    should_republish,
)
from .regime import MarketRegime, RegimeSample, classify_regime
from .registry import (
    CURATED_ACCOUNTS,
    IDEA_ONLY_ACCOUNTS,
    TIER_A_ACCOUNTS,
    TIER_B_ACCOUNTS,
    TIER_C_ACCOUNTS,
    AccountPerformance,
    SocialFetchPlan,
    SocialSignal,
    build_signal,
    is_muted,
    measure_account,
    plan_social_fetch,
    registry_snapshot,
    signal_edge_state,
)
from .replay import (
    PerformanceReport,
    PromotionVerdict,
    ReplayObservation,
    TradeRecord,
    attribute_loss,
    compare_policies,
    detect_drift,
    evaluate_promotion,
    replay_policy,
    summarize_trades,
)
from .smartmoney import (
    SmartMoneyAssessment,
    WalletOutcome,
    WalletReputation,
    assess_smart_money,
    build_reputation,
    classify_wallet,
    decay_reputation,
)
from .timeline import Provenance, TokenEvent, TokenTimeline, observation_events

#: The lab has no live-execution adapter in this release, by design.
LIVE_EXECUTION_ENABLED = False

__all__ = [
    "CHALLENGER_STRATEGY_VERSION",
    "CURATED_ACCOUNTS",
    "DEFAULT_LAB_CONFIG",
    "ENTRY_DECISIONS",
    "IDEA_ONLY_ACCOUNTS",
    "LIFECYCLE_STATES",
    "LIVE_EXECUTION_ENABLED",
    "NO_DESCRIPTION",
    "STRATEGY_VERSION",
    "TIER_A_ACCOUNTS",
    "TIER_B_ACCOUNTS",
    "TIER_C_ACCOUNTS",
    "AccountPerformance",
    "AllocationCandidate",
    "AuthenticityAssessment",
    "BankrollState",
    "BreakerInputs",
    "BreakerStatus",
    "Decision",
    "EntryContext",
    "EntryEvaluation",
    "EvidenceQuality",
    "ExitContext",
    "ExitJournalEntry",
    "ExitPlan",
    "ExpectedEdge",
    "LabConfig",
    "LifecycleObservation",
    "ManipulationGraph",
    "MarketRegime",
    "PaperPosition",
    "PerformanceReport",
    "PromotionVerdict",
    "Provenance",
    "PublicationState",
    "RealizedPnl",
    "Reason",
    "ReentryAssessment",
    "RegimeSample",
    "ReplayObservation",
    "RepublishDecision",
    "RoundTripCost",
    "SafetyStatus",
    "SizingInputs",
    "SizingResult",
    "SmartMoneyAssessment",
    "SocialFetchPlan",
    "SolActivityProfile",
    "SocialSignal",
    "TokenEvent",
    "TokenIdentity",
    "TokenLifecycle",
    "TokenTimeline",
    "TradeDecision",
    "TradeRecord",
    "WalletActivity",
    "WalletOutcome",
    "WalletReputation",
    "advance_lifecycle",
    "aggregate_sol_activity",
    "allocate_capital",
    "apply_exit",
    "assess_economic_authenticity",
    "assess_reentry",
    "assess_smart_money",
    "attribute_loss",
    "build_manipulation_graph",
    "build_reputation",
    "build_signal",
    "build_token_identity",
    "classify_regime",
    "classify_wallet",
    "compare_policies",
    "decay_reputation",
    "decision_from_json",
    "decision_to_json",
    "detect_drift",
    "estimate_expected_edge",
    "estimate_round_trip_cost",
    "evaluate_circuit_breakers",
    "evaluate_entry",
    "evaluate_promotion",
    "human_reason",
    "is_muted",
    "lab_config_from_settings",
    "leg_costs",
    "lifecycle_from_json",
    "lifecycle_to_json",
    "measure_account",
    "new_lifecycle",
    "observation_events",
    "observe",
    "open_position",
    "plan_exit",
    "plan_social_fetch",
    "position_from_json",
    "position_to_json",
    "registry_snapshot",
    "replay_policy",
    "safe_image_url",
    "should_republish",
    "signal_edge_state",
    "size_position",
    "summarize_trades",
    "why_not_entry",
]
