"""GMGN OpenAPI research integration — read operations only.

Built against the official ``GMGNAI/gmgn-skills`` client at commit ``267ff6b``.
The package is deliberately layered so that only one file can reach the network:

* :mod:`.signals` — GMGN's documented enums, restated; nothing guessed.
* :mod:`.models` — parsed rows, with exact-mint identity enforced at the door.
* :mod:`.lifecycle` — one record per mint, from new pair to second leg.
* :mod:`.health` — truthful provider states, and the inference they forbid.
* :mod:`.budget` — cache, coalescing, rationing and the circuit breaker.
* :mod:`.client` — the only module here that imports an HTTP client, and the
  only one that ever sees the credential.

Nothing in this package can place an order: the signed-auth mode GMGN requires
for trading is not implemented, no private key is read, and the request path
asserts every call against a read-only allow-list.
"""

from __future__ import annotations

from .budget import (
    ALLOW,
    DENY_BREAKER_OPEN,
    DENY_BUDGET,
    DENY_DISABLED,
    DENY_RATE_LIMITED,
    TTL_BY_KIND,
    BudgetConfig,
    RequestBudget,
)
from .client import (
    DEFAULT_HOST,
    ORDER_PATHS,
    READ_PATHS,
    GmgnClient,
    GmgnError,
    redact,
)
from .health import (
    ACTIVE,
    ACTIVE_NO_EVENTS,
    AUTH_MISSING,
    AUTH_REJECTED,
    DISABLED_BY_CONFIG,
    HEALTHY_STATES,
    HUMAN_STATE,
    PROVIDER_DEGRADED,
    RATE_LIMIT_BANNED,
    RATE_LIMITED,
    STATES,
    TIMEOUT,
    UNKNOWN,
    UNKNOWN_STATES,
    ProviderHealth,
    record_failure,
    record_success,
)
from .lifecycle import (
    BOARD_FINAL_STRETCH,
    BOARD_MIGRATED,
    BOARD_NEW_PAIRS,
    BOARD_SECTIONS,
    CONTINUATION,
    DEAD,
    EARLY_CURVE,
    FADING,
    FINAL_STRETCH,
    GRADUATING,
    MID_CURVE,
    NEAR_COMPLETION,
    NEW_PAIR,
    POST_GRADUATION,
    PRE_GRADUATION,
    PUMPSWAP,
    RECENTLY_MIGRATED,
    STAGES,
    TOKEN_CREATED,
    TRENDING,
    StageConfig,
    StageMark,
    TokenLifecycle,
    advance,
    board_section,
    classify_stage,
    group_board,
    lifecycle_from_json,
    open_lifecycle,
)
from .models import (
    GmgnParticipant,
    GmgnSecurity,
    GmgnSignal,
    GmgnToken,
    GmgnWalletTrade,
    parse_hot_searches_response,
    parse_participants,
    parse_rank_response,
    parse_security,
    parse_signals,
    parse_tokens,
    parse_trenches_response,
    parse_wallet_trades,
)
from .signals import (
    CHAIN_SOLANA,
    DEMAND_SIGNALS,
    DISTRIBUTION_SIGNALS,
    PARTICIPANT_TAGS,
    PLACEMENT_SIGNALS,
    PRICE_CHANGE_INTERVALS,
    PROVIDER_TAGS,
    RANK_INTERVALS,
    SIGNAL_TYPES,
    SIGNAL_UNKNOWN,
    TAG_BOT_PROVEN_DISTRIBUTOR,
    TAG_BOT_PROVEN_EARLY,
    TAG_GMGN_KOL,
    TAG_GMGN_SMART_MONEY,
    TRENCH_COMPLETED,
    TRENCH_NEAR_COMPLETION,
    TRENCH_NEW_CREATION,
    TRENCH_TYPES,
    SignalClassification,
    classify_signal,
    is_demand_signal,
    signal_name,
)

#: The upstream commit this integration was written against.  Recorded so a
#: future reader can diff the contract rather than re-derive it.
GMGN_SOURCE_COMMIT = "267ff6ba86aaeb5d4a4f23409b3cfef7ef32ff62"
GMGN_SOURCE_REPO = "https://github.com/GMGNAI/gmgn-skills"

__all__ = [
    "ACTIVE",
    "ACTIVE_NO_EVENTS",
    "ALLOW",
    "AUTH_MISSING",
    "AUTH_REJECTED",
    "BOARD_FINAL_STRETCH",
    "BOARD_MIGRATED",
    "BOARD_NEW_PAIRS",
    "BOARD_SECTIONS",
    "CHAIN_SOLANA",
    "CONTINUATION",
    "DEAD",
    "DEFAULT_HOST",
    "DEMAND_SIGNALS",
    "DENY_BREAKER_OPEN",
    "DENY_BUDGET",
    "DENY_DISABLED",
    "DENY_RATE_LIMITED",
    "DISABLED_BY_CONFIG",
    "DISTRIBUTION_SIGNALS",
    "EARLY_CURVE",
    "FADING",
    "FINAL_STRETCH",
    "GMGN_SOURCE_COMMIT",
    "GMGN_SOURCE_REPO",
    "GRADUATING",
    "HEALTHY_STATES",
    "HUMAN_STATE",
    "MID_CURVE",
    "NEAR_COMPLETION",
    "NEW_PAIR",
    "ORDER_PATHS",
    "PARTICIPANT_TAGS",
    "PLACEMENT_SIGNALS",
    "POST_GRADUATION",
    "PRE_GRADUATION",
    "PRICE_CHANGE_INTERVALS",
    "PROVIDER_DEGRADED",
    "PROVIDER_TAGS",
    "PUMPSWAP",
    "RANK_INTERVALS",
    "RATE_LIMIT_BANNED",
    "RATE_LIMITED",
    "READ_PATHS",
    "RECENTLY_MIGRATED",
    "SIGNAL_TYPES",
    "SIGNAL_UNKNOWN",
    "STAGES",
    "STATES",
    "TAG_BOT_PROVEN_DISTRIBUTOR",
    "TAG_BOT_PROVEN_EARLY",
    "TAG_GMGN_KOL",
    "TAG_GMGN_SMART_MONEY",
    "TIMEOUT",
    "TOKEN_CREATED",
    "TRENCH_COMPLETED",
    "TRENCH_NEAR_COMPLETION",
    "TRENCH_NEW_CREATION",
    "TRENCH_TYPES",
    "TRENDING",
    "TTL_BY_KIND",
    "UNKNOWN",
    "UNKNOWN_STATES",
    "BudgetConfig",
    "GmgnClient",
    "GmgnError",
    "GmgnParticipant",
    "GmgnSecurity",
    "GmgnSignal",
    "GmgnToken",
    "GmgnWalletTrade",
    "ProviderHealth",
    "RequestBudget",
    "SignalClassification",
    "StageConfig",
    "StageMark",
    "TokenLifecycle",
    "advance",
    "board_section",
    "classify_signal",
    "classify_stage",
    "group_board",
    "is_demand_signal",
    "lifecycle_from_json",
    "open_lifecycle",
    "parse_hot_searches_response",
    "parse_participants",
    "parse_rank_response",
    "parse_security",
    "parse_signals",
    "parse_tokens",
    "parse_trenches_response",
    "parse_wallet_trades",
    "record_failure",
    "record_success",
    "redact",
    "signal_name",
]
